### ISSUE TITLE
Cloudsim v4 examples not working

### ISSUE THREAD

**Issue by alexander989** [Cloudslab/cloudsim#102]
Hello 

I was trying to experiment on CloudSim. Most of the tutorials for installation available are for version 3.0.3. When trying to apply the same instruction on v4, examples don´t seem to work. 
I'm using Netbeans , added the Jar files to the library ( cloudsim 4.0 and cloudsim-examples 4.0),still the examples won´t work. It is either that some files are missing or the tutorials for installing 3.0.3 does not match the 4.0 version. 
Could you plz provide a youtube video or a complete instructions about the installation process for version 4.0.
Thanks

**Comment by chloechj** [comment]
The version 4 has managed with maven, well, you can use the way of import the cloudsim v4 with maven .
