### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by M-Razavi** [Cloudslab/cloudsim#112]
CloudSim jarfiles and sources could be found on Maven repository?

**Comment by moguzozcan** [comment]
I think they are created when you compile the project using 'mvn package' command.

**Comment by armanriazi** [comment]
@moguzozcan How to run examples with maven? Is there anyway that I can execute java files in maven?

**Comment by moguzozcan** [comment]
mvn exec:java -Dexec.mainClass="write the main class" -Dexec.args="arg0 arg1 arg2"

**Comment by M-Razavi** [comment]
@moguzozcan To have Clouldsim's artifacts on The MavenCentral, It required some steps to be done [manually](https://dzone.com/articles/publish-your-artifacts-to-maven-central) or [automatically](https://github.com/marketplace/actions/action-maven-publish).

**Comment by armanriazi** [comment]
@moguzozcan Thanks, I had to reinstall new updates  maven,netbeans,jdk
