### ISSUE TITLE
How can i simulation dag task on cloudsim?

### ISSUE THREAD

**Issue by bowang1993** [Cloudslab/cloudsim#116]
who can helo me ,please......

**Comment by bowang1993** [comment]
help

**Comment by chloechj** [comment]
ok,you can use the toolkit that WorkflowSim to simulate.

**Comment by bowang1993** [comment]
Well, it's just that I see a lot of other papers that are simulated with cloudsim.

**Comment by chloechj** [comment]
Original cloudsim code have no workflow classes, so, we can't simulate in it.

**Comment by bowang1993** [comment]
ok , thank you very much!!

**Comment by deRemo** [comment]
Hi @bowang1993,

CloudSim7G comes bundled with a revised network module that allows dag simulations (although it is not as advanced as WorkflowSim), check the network/datacenter folder in cloudsim-examples
