### ISSUE TITLE
Container scheduling How 

### ISSUE THREAD

**Issue by raji2401** [Cloudslab/cloudsim#129]

**Comment by raji2401** [comment]
How and where 
I can specify number of conatiners required for my project

**Comment by GitHubDiom** [comment]
hi  @raji2401,
Have you solved this problem?
i am trying to simulate a scheduling process, but it confused me to figure out that how to scheduling containers with run the 'ContainerClousSimExample1.java' code

**Comment by raji2401** [comment]
No...

**Comment by GitHubDiom** [comment]
Are you still doing this work, can we discuss it? privately

**Comment by GitHubDiom** [comment]
@raji2401  Are you still doing this work, can we discuss it? privately
