### ISSUE TITLE
Error while building project version 4.0 from Maven with 'mvn package' command

### ISSUE THREAD

**Issue by moguzozcan** [Cloudslab/cloudsim#131]
Hello,
I am getting an error while I am trying to build the project from maven. I am in the root folder where the main pom.xml file is located and I am running 'mvn package' command as it is suggested in the pom file itself. I am pasting the stack trace below. Anyone has any idea?
Thanks,
Oguz

[WARNING] Warning building bundle org.cloudbus.cloudsim:cloudsim-toolkit:bundle:4.0 : Classpath is empty. Private-Package and Export-Package can only expand from the classpath when there is one
[WARNING] Warning building bundle org.cloudbus.cloudsim:cloudsim-toolkit:bundle:4.0 : Instructions in Private-Package, or -testpackages that are never used: .*
[WARNING] Warning building bundle org.cloudbus.cloudsim:cloudsim-toolkit:bundle:4.0 : Instructions in Export-Package that are never used: org\.cloudbus\.cloudsim\..*|org\.cloudbus\.cloudsim
[WARNING] Warning building bundle org.cloudbus.cloudsim:cloudsim-toolkit:bundle:4.0 : Superfluous export-package instructions: [org.cloudbus.cloudsim.*]
[ERROR] Error building bundle org.cloudbus.cloudsim:cloudsim-toolkit:bundle:4.0 : The JAR is empty
[ERROR] Error(s) found in bundle configuration
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.106 s
[INFO] Finished at: 2019-04-09T23:04:31+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:2.0.1:bundle (default-bundle) on project cloudsim-toolkit: Error(s) found in bundle configuration -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by skardani** [comment]
no worries. We just released cloudsim 5.0. Download and try that. any problem, please let us know.
