### ISSUE TITLE
The main repository doesn't contain the docs and Jar folders !

### ISSUE THREAD

**Issue by Sabir97** [Cloudslab/cloudsim#135]
In github i found many versions of CloudSim, but the problem is that the version 3 still the most clear and clean one, i don't know why in some releases they don't include the docs like in version 3.0.3, also in cloudsim 4, i found two packages, one that includes only the class files, and the other with the source files, i mean why don't they just put everything in one single asset, and in the main repository they did't include the docs folder, even though it's really important, also they did't include the jar folder that has the jar files which contains source and classes with exemples.

**Comment by jmsw4bn** [comment]
I also found this problem. The missing of jar files leads to many errors. Maven automatically downloads these files from its online repository, while, these files are also not existed in the online repository.

**Comment by Sabir97** [comment]
The JAR files are not necessary if you have the source code, you can create your own jar files by putting the source code into JAR package,  the jar files are mostly used to import classes into the project because the classes depend on other classes outside the project, but you can still use the source code directly and you just need Common Maths JAR file to import into the project.
