### ISSUE TITLE
The cloudsim-5 has errors related to Maven

### ISSUE THREAD

**Issue by jmsw4bn** [Cloudslab/cloudsim#138]
I downloaded the cloudsim-5，but I found no jar files or source code in the folder.
When I built cloudsim-5 with 'mvn package' command, I got some errors, such as the error list below:

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.cloudbus.cloudsim:distribution:4.0: Failure to find org.cloudbus.cloudsim:cloudsim-package:pom:4.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 11

Are there no related files in the on-line repository of Maven?
How can I get all the needed files to built cloudsim-5?

**Comment by Sabir97** [comment]
download the zip file again, and extract it you should find the source code in the modules folder, and you can create the jar files on your own
