### ISSUE TITLE
Problem in Consts.java

### ISSUE THREAD

**Issue by alitariqnet** [Cloudslab/cloudsim#147]
// ================== Time constants ==================
    /** One minute time in seconds. */
    public static final int MINUTE = 60;
    /** One hour time in seconds. */
    public static final int HOUR = 60 * MINUTE;
    /** One day time in seconds. */
    public static final int DAY = 24 * HOUR;
    /** One week time in seconds. */
    public static final int WEEK = 24 * HOUR;

Above lines are written in Consts.java in Cloudsim 5.0 pre-release
Do you think that the last line should be,
/** One week time in seconds. */
    public static final int WEEK = 7 * DAY;
?

**Comment by lak-sh-mi** [comment]
Looking at the logic if it is to represent seconds as stated in comments
week = 7 * day

This bug may not be obvious of the constant week is not used in the
implementations of the tool.
Did we know it the usage if week?

**Comment by deRemo** [comment]
Fixed in 15232d2c8eaac5e08c18eca524aace0fd19eaeac
