### ISSUE TITLE
Bug on jdk17-lts

### ISSUE THREAD

**Issue by thweetkomputer** [Cloudslab/cloudsim#172]
I ran CloudSimExample8 and this error was raised.
<img width="882" alt="image" src="https://github.com/Cloudslab/cloudsim/assets/47818277/4a2163de-6e7c-433b-a8a9-497aa32ea2d5">

Maybe line 512 need not to be modified with iterator.

**Comment by deRemo** [comment]
This has been fixed in f252a41c0ec882e67f33a546998a9729b899f36c
