### ISSUE TITLE
How to install and configure  CloudSim v6.0.0-beta on Eclipse?

### ISSUE THREAD

**Issue by MegiTartari3** [Cloudslab/cloudsim#174]
Hello!Please as I am a new researcher in the field of cloud , I need to start experimenting with CloudSim. I want to start using it through eclipse, but I don't know how to configure.I have downloaded the 'sourcecode.zip' for the latest version. Can you please guide me to configure it on eclipse to start testing the examples?
Thank you,
Megi Tartari

**Comment by itconsultore** [comment]
you could create a new project in Eclipse and use Maven to add the CloudSim libraries.
You can follow the source code of CloudSim examples to personalise the experiments.

**Comment by deRemo** [comment]
Use CloudSim 7G (pre-release), it should work out-of-the-box on Eclipse too
