### ISSUE TITLE
CloudSimExample8.java is not working

### ISSUE THREAD

**Issue by Raove** [Cloudslab/cloudsim#187]
I've ran the other tests and they work just fine, but this test with entities seems to be broken, I am running the recommended java version and I haven't changed any of the original code, I just ran the tests. 
![image](https://github.com/user-attachments/assets/5098f625-8f8a-4dbd-ab1f-8815add9e6f7)
If anyone has a fix or any idea as to what is causing this, I would like to know asap.

**Comment by Astabol** [comment]
Hello @Raove,
Kindly Provide the following details to recreate the issue:
**1. JAVA Version
2. CloudSim Version**

Thank You

**Comment by Raove** [comment]
I am using CloudSim 7 and Java 23

**Comment by Raove** [comment]
fixed by #191
