### ISSUE TITLE
CloudSimExample6 is Not Working Due to Null Pointer Exception

### ISSUE THREAD

**Issue by Astabol** [Cloudslab/cloudsim#188]
Hello Folks,
While Executing of _CloudSimExample6.java_ is encountered Null Pointer Exception.

**Snapshot Attached Below:**
![image](https://github.com/user-attachments/assets/2ac8a4cf-04ce-452d-a153-c4544836fae3)

**Current Result Vs Expected Result**
_**Current Result:**_ Throwing Null Exception
**_Expected Result:_** It should execute correctly without any error

**Java Version:** 21 & 23
**CloudSim Version:** 7.0

**How to Regenerate the issue:** Simply Execute the CloudSimExample6.java, It will be recreated.

Thank You

**Comment by deRemo** [comment]
Hi @Astabol 

I've fixed it in my (private) work-in-progress patch to CloudSim7G. I can't share the code yet, unfortunately, but you could try to apply the patch yourself in the meantime (just don't commit it locally, or you'll eventually have a merge conflict with the official release)


Just add:
```Java
if (host == null) {
        return false;
 }
```

At the beginning of `allocateHostForGuest(GuestEntity guest, HostEntity host)` method in `VmAllocationPolicy.java
`

**Comment by Astabol** [comment]
Thanks @deRemo
