### ISSUE TITLE
cloudsim-4.0-sources jar file missing

### ISSUE THREAD

**Issue by lakhanqurban** [Cloudslab/cloudsim#93]
In the latest version cloudsim 4.0, cloudsim-4.0-sources.jar and cloudsim-example-4.0-sources are missing in the available zip files, because of this, I am unable to run the container examples as I need to work on the containers. please help me regarding the said problem. 

Regards

**Comment by xiechengsheng** [comment]
Hi, did you simulate the container scheduler's process by cloudsim successfully? Is there any difference between container scheduler simulation process and task scheduler simulation process?
